name: Deploy to Vercel
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run tests
        run: npx nx test task-manager --configuration=ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npx nx build task-manager --configuration=production

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Pulling Vercel environment information..."
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN

          echo "Building project..."
          vercel build --prod --token=$VERCEL_TOKEN

          echo "Deploying to Vercel..."
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN)
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

          echo "✅ Deployment successful! URL: $DEPLOYMENT_URL"
